### ISSUE TITLE
Latest release on https://pkg.go.dev

### ISSUE THREAD

**Issue by agillesCoveo** [nasa9084/go-switchbot#23]
Hi!

I'm trying to fetch a Plug mini and I have an error because of the deviceStatus.Voltage type being an int instead of float. When I looked at the repo, I saw it was the correct type and realized I'm using v1.0.0.

I trygin go get -u ./... and setting it manually to v3.1.0 (latest tag I see here) but it doesn't work.

Going to https://pkg.go.dev/github.com/nasa9084/go-switchbot, I see v1.0.0 as the latest release.

Is it something I'm missing here?

**Comment by AlbinOS** [comment]
I'm sorry, I just figured it out playing with go mod & the /v3 suffix... I didn't do Go in a long time 😅

**Comment by agillesCoveo** [comment]
I'm sorry, I just figured it out playing with go mod & the /v3 suffix... I didn't do Go in a long time 😅

**Comment by agillesCoveo** [comment]
I'm sorry, I just figured it out playing with go mod & the /v3 suffix... I didn't do Go in a long time 😅
